indexing-settings:
  sites:
#    - url: https://et-cetera.ru/mobile/
#      name: Театр et-cetera
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://www.lutherancathedral.ru/
#      name: Кафедральный собор Святых Петра и Павла
#    - url: https://sinara-center.com/gallery/
#      name: синара центр
    - url: https://ugmk-telecom.ru/
      name: УГМК-Телеком

server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: rootadminroot
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 60000
      pool-name: SearchEngineHikariPool
      connection-test-query: SELECT 1
      validation-timeout: 3000
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        flush_mode: COMMIT
        generate_statistics: false
  main:
    allow-bean-definition-overriding: true

connect:
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36
  referrer: http://www.google.com

file:
  extensions: pdf|PDF|docx?|DOCX?|xlsx?|XLSX?|pptx?|PPTX?|jpe?g|JPE?G|gif|GIF|png|PNG|mp3|MP3|mp4|MP4|aac|AAC|json|JSON|csv|CSV|exe|EXE|apk|APK|rar|RAR|zip|ZIP|xml|XML|jar|JAR|bin|BIN|svg|SVG|nc|NC|webp|WEBP|m|M|fig|FIG|eps|EPS

snippet:
  border: 5

page:
  frequency:
    limit: 95

error:
  interrupted: Indexing stopped by user
  certificate: Site's certificate validity check failed
  unknown: Unknown error

logging:
  level:
    root: INFO
